# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: kongpatrick97@gmail.com
description: I'm a Statistics Undergraduate at the University of British Columbia in my third year.
baseurl: "http://mattcouchman.co.uk/jekyll-resume/"
url: "pkong97.github.io"
name: Patrick Kong
location: Vancouver, BC
languages: Python, Java, SQL
github_username:  pkong97
email_address: kongpatrick97@email.com

# Build settings
markdown: kramdown
